let tasks = [{
    "id": 0,
    "progress": "toDo",
    "category": "Sales",
    "headline": "Test mit ID0",
    "description": "Modify the contents of the main website test test test test",
    "dueDate": "2022-12-08",
    "prio": "medium",
    "subTask": "Make Icon",
    "tasksOverall": 3,
    "tasksDone": 1,
    "tasksPercent": '',
    "assignet": [{
            "firstName": 'Lukas',
            "lastName": 'Neureiter',
            "initials": 'LN',
        },
        {
            "firstName": 'Ilmar',
            "lastName": 'Kerner',
            "initials": 'IK',
        },
        {
            "firstName": 'Dennis',
            "lastName": 'Frese',
            "initials": 'DF',
        }
    ],
},
{
    "id": 1,
    "progress": "done",
    "category": "Sales",
    "headline": "Test mit ID1",
    "description": "Modify the contents of the main website test test test test",
    "dueDate": "2022-12-15",
    "prio": "urgent",
    "subTask": "Make Icon",
    "tasksOverall": 2,
    "tasksDone": 1,
    "tasksPercent": '',
    "assignet": [{
            "firstName": 'Lukas',
            "lastName": 'Neureiter',
            "initials": 'LN',
        },
        {
            "firstName": 'Ilmar',
            "lastName": 'Kerner',
            "initials": 'IK',
        },
        {
            "firstName": 'Dennis',
            "lastName": 'Frese',
            "initials": 'DF',
        }
    ],
},
{
    "id": 7,
    "progress": "inProgress",
    "category": "Sales",
    "headline": "Test mit ID7",
    "description": "Modify the contents of the main website test test test test",
    "dueDate": "2022-12-30",
    "prio": "urgent",
    "subTask": "Make Icon",
    "tasksOverall": 2,
    "tasksDone": 1,
    "tasksPercent": '',
    "assignet": [{
            "firstName": 'Lukas',
            "lastName": 'Neureiter',
            "initials": 'LN',
        },
        {
            "firstName": 'Ilmar',
            "lastName": 'Kerner',
            "initials": 'IK',
        },
        {
            "firstName": 'Dennis',
            "lastName": 'Frese',
            "initials": 'DF',
        }
    ],

},
{
    "id": 4,
    "progress": "inProgress",
    "category": "Sales",
    "headline": "Test mit ID1",
    "description": "Modify the contents of the main website test test test test",
    "dueDate": "2022-11-02",
    "prio": "urgent",
    "subTask": "Make Icon",
    "tasksOverall": 2,
    "tasksDone": 1,
    "tasksPercent": '',
    "assignet": [{
            "firstName": 'Lukas',
            "lastName": 'Neureiter',
            "initials": 'LN',
        },
        {
            "firstName": 'Ilmar',
            "lastName": 'Kerner',
            "initials": 'IK',
        },
        {
            "firstName": 'Dennis',
            "lastName": 'Frese',
            "initials": 'DF',
        }
    ],
},
{
    "id": 2,
    "progress": "toDo",
    "category": "Sales",
    "headline": "Test mit ID2",
    "description": "Modify the contents of the main website test test test test",
    "dueDate": "2022-10-03",
    "prio": "urgent",
    "subTask": "Make Icon",
    "tasksOverall": 2,
    "tasksDone": 1,
    "tasksPercent": '',
    "assignet": [{
            "firstName": 'Lukas',
            "lastName": 'Neureiter',
            "initials": 'LN',
        },
        {
            "firstName": 'Ilmar',
            "lastName": 'Kerner',
            "initials": 'IK',
        },
        {
            "firstName": 'Dennis',
            "lastName": 'Frese',
            "initials": 'DF',
        }
    ],
},
{
    "id": 3,
    "progress": "awaitingFeedback",
    "category": "Design",
    "headline": "Test mit ID3",
    "description": "Modify the contents of the main website test test test test",
    "dueDate": "2022-12-04",
    "prio": "low",
    "subTask": "Make Icon",
    "tasksOverall": 3,
    "tasksDone": 2,
    "tasksPercent": '',
    "assignet": [{
            "firstName": 'Lukas',
            "lastName": 'Neureiter',
            "initials": 'LN',
        },
        {
            "firstName": 'Ilmar',
            "lastName": 'Kerner',
            "initials": 'IK',
        },
        {
            "firstName": 'Dennis',
            "lastName": 'Frese',
            "initials": 'DF',
        }
    ],
},
{
    "id": 8,
    "progress": "awaitingFeedback",
    "category": "Design",
    "headline": "Test mit ID3",
    "description": "Modify the contents of the main website test test test test",
    "dueDate": "2022-12-04",
    "prio": "low",
    "subTask": "Make Icon",
    "tasksOverall": 3,
    "tasksDone": 2,
    "tasksPercent": '',
    "assignet": [{
            "firstName": 'Lukas',
            "lastName": 'Neureiter',
            "initials": 'LN',
        },
        {
            "firstName": 'Ilmar',
            "lastName": 'Kerner',
            "initials": 'IK',
        },
        {
            "firstName": 'Dennis',
            "lastName": 'Frese',
            "initials": 'DF',
        }
    ],
},
{
    "id": 4,
    "progress": "awaitingFeedback",
    "category": "toDo",
    "headline": "Test mit ID4",
    "description": "Modify the contents of the main website test test test test",
    "dueDate": "2022-12-04",
    "prio": "low",
    "subTask": "Make Icon",
    "tasksOverall": 3,
    "tasksDone": 2,
    "tasksPercent": '',
    "assignet": [{
            "firstName": 'Lukas',
            "lastName": 'Neureiter',
            "initials": 'LN',
        },
        {
            "firstName": 'Ilmar',
            "lastName": 'Kerner',
            "initials": 'IK',
        },
        {
            "firstName": 'Dennis',
            "lastName": 'Frese',
            "initials": 'DF',
        }
    ],
}
];